version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: is-business-day-app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
  web:
    image: nginx:alpine
    container_name: is-business-day-nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge